### ISSUE TITLE
Bypass host blacklist check by adding dot in the end of the hostname

### ISSUE THREAD

**Issue by vladmiller** [wkcaj/safecurl#6]
Hi,

You can bypass hostname check if you add a dot in the end of hostname

http://safecurl.fin1te.net./

**Comment by wkcaj** [comment]
Hey,

Cheers for reporting this. I originally had this sorted in my own regex ("safecurl.fin1te.net.?"), however the changes got over-written.

There has been another issue raised regarding the use of regexes - Issue #7. I think rather than persuading a user to write a solid regex (which might be hard), I'll re-think the domain check.

I'll close this issue and work on Issue #7.

Jack
